name: Builds
on: [pull_request, push]
jobs:
  prepare:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v4
      - uses: cachix/cachix-action@v8
        with:
          name: kwbauson
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
  homeConfigurations.kwbauson:
    needs: prepare
    steps:
      - run: nix-build -A cfg.homeConfigurations.kwbauson
