name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: ${{ matrix.output }}
    strategy:
      fail-fast: false
      matrix:
        output:
          - nixosConfigurations.keith-xps.drv
          - nixosConfigurations.kwbauson.drv
          - nixosConfigurations.keith-vm.drv
          - homeConfigurations.graphical
          - homeConfigurations.non-graphical
    runs-on: ubuntu-20.04
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: kwbauson.com
          username: keith
          key: ${{ secrets.PRIVATE_KEY }}
          script: nix --tarball-ttl 0 --no-link github:kwbauson/cfg?rev=${{ github.sha }}#${{ matrix.output }}
