name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: ${{ matrix.output }}
    strategy:
      fail-fast: false
      matrix:
        output:
          - nixosConfigurations.keith-xps
          - nixosConfigurations.kwbauson
          - nixosConfigurations.keith-vm
          - homeConfigurations.non-graphical
          - homeConfigurations.graphical
          - homeConfigurations.keith-mac
    runs-on: ${{ ! endsWith(matrix.output, '-mac') && 'ubuntu' || 'macos' }}-latest
    steps:
      - uses: actions/cache@v2
        with:
          key: ${{ matrix.output }}-cache
          path: ~/.cache/nix
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v4
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kwbauson
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#${{ matrix.output }} && cd result && pwd -P
      - uses: actions/upload-artifact@v2
        with:
          name: nix-${{ matrix.output }}-cache
          path: ~/.cache/nix
