name: Builds
on: [pull_request, push]
jobs:
  build:
    name: ${{ matrix.output }}
    strategy:
      fail-fast: false
      matrix:
        output:
          - nixosConfigurations.keith-xps.drv
          - nixosConfigurations.kwbauson.drv
          - nixosConfigurations.keith-vm.drv
          - homeConfigurations.keith-xps
          - homeConfigurations.kwbauson
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nixbuild/nix-quick-install-action@v4
      - uses: cachix/cachix-action@v8
        with:
          name: kwbauson
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix run -f . nix-build-uncached -c nix-build-uncached -A cfg.${{ matrix.output }}
