name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: ${{ matrix.output }}
    strategy:
      fail-fast: false
      matrix:
        output:
          - nixosConfigurations.keith-xps.drv
          - nixosConfigurations.kwbauson.drv
          - nixosConfigurations.keith-vm.drv
          - homeConfigurations.graphical
          - homeConfigurations.non-graphical
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        dir=$(ssh keith@kwbauson.com mktemp -d)
