name: Build
on: { workflow_dispatch, push: { branches: [main] }, pull_request }
jobs:
  build:
    runs-on: self-hosted
    env:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
    steps:
      - run: nix -vL --show-trace build github:${{ github.repository }}/${{ github.sha }}
      - run: cachix push kwbauson result
