name: Check for updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nixbuild/nix-quick-install-action@v4
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v8
        with:
          name: kwbauson
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix shell .#nle -c nle update
      - run: nix flake update --override-input nixpkgs github:NixOS/nixpkgs
