name: Check for updates
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v4
        with:
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes ca-references
      - uses: cachix/cachix-action@v8
        with:
          name: kwbauson
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix profile install .#nle
      - run: nle update
      - run: nle generate
      - uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: Automatic update
          commit-message: automatic update
          branch: automatic-update
          token: ${{ secrets.PAT }}
